const NEO_JOKES = [
  "Are you a campfire? because my heart is already racing just thinking about you. \ud83d\udc93",
  "You're the peanut butter to my jelly. Most of the time, anyway. \ud83d\ude02",
  "Are you a duck? Because you quack me up. \ud83e\udd86",
  "You are the only person I'd actually share my snacks with. Don't tell anyone I said that, though.",
  "I love you more than bubble tea... and you're way sweeter too!",
  "You're my absolute favorite notification. Now wake up so I can annoy you. \ud83e\udd70",
  "You are the cutest duck in the pond. Quack quack!",
  "I love you a waddle lot. \ud83e\udd86",
  "My hands are feeling a bit cold, because you are looking super hot right now. \ud83d\udd25",
  "You literally have my whole heart in your hands. But my arm is completely numb now.",
  "I love you more than bubble tea... and that is saying a lot.",
  "Are you a magician? because you've been running through my dirty mind all day. \ud83d\udca6",
  "My hands are feeling a bit cold, but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "Even the cutest duck is jealous of how pretty NEO Baby is. I mean it from the bottom of my heart!",
  "You're lazier than a koala, but twice as cute. Please don't let it go to your head.",
  "You must be exhausted, but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "I love you a waddle lot. Quack quack!",
  "I don't even need to work out today, because you are looking super hot right now. \ud83d\udd25",
  "Are you a magician? because my heart is already racing just thinking about you. \ud83d\udc93",
  "NEO Baby, you're accused of making me smile like an idiot, you owe me a giant hug.",
  "I love you more than pizza... well, almost.",
  "Even the cutest duck is jealous of how pretty NEO Baby is. \ud83e\udd86",
  "You ruffle my feathers in the best way possible. I mean it from the bottom of my heart!",
  "You're lazier than a koala, but twice as cute. But my arm is completely numb now.",
  "NEO Baby, you're accused of making me miss you this much, you are sentenced to a lifetime with me.",
  "NEO Baby, you're accused of being illegally cute, I'm calling the cute police.",
  "You ruffle my feathers in the best way possible. Wait, is that too cheesy?",
  "You snore cutely, but I'll never admit that out loud. But my arm is completely numb now.",
  "You snore cutely, but I'll never admit that out loud. NEO Baby, you're simply my favorite.",
  "Stop being so ducking cute all the time. Quack quack!",
  "NEO Baby, you're accused of making my heart skip a beat, your punishment is a million kisses.",
  "You're my absolute favorite notification. NEO Baby, you're simply my favorite.",
  "NEO Baby, you're accused of being illegally cute, I demand a cuddle session immediately.",
  "I love you more than cake... but if we have only one bite left, we're fighting.",
  "Are you a magician? because I want you on top of me. \ud83e\udd75",
  "NEO Baby, you're accused of looking too pretty today, I'm calling the cute police.",
  "I love you more than pancakes... and that is saying a lot.",
  "I love you more than bubble tea... but please don't make me prove it by sharing.",
  "My hands are feeling a bit cold, because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "I love you more than ice cream... and that is saying a lot.",
  "You are the only person I'd actually share my snacks with. I really hope that made you smile today!",
  "You look so peaceful when you sleep. But my arm is completely numb now.",
  "You're the only duck I want to waddle through life with. \ud83d\udc95",
  "You're officially my favorite headache in the world. NEO Baby, you're stuck with me forever.",
  "Do you have a map? because I want you on top of me. \ud83e\udd75",
  "You're officially my favorite headache in the world. And I seriously wouldn't trade you for the world.",
  "You are the cutest duck in the pond. Wait, is that too cheesy?",
  "I love your cute smile, because you are looking super hot right now. \ud83d\udd25",
  "Are you a magician? because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "Even the cutest duck is jealous of how pretty NEO Baby is. \ud83d\udc95",
  "Are you a magician? and honestly I am starving. \ud83d\ude08",
  "You're looking like a whole snack today, because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "I love you more than you love your morning coffee... and you're way sweeter too!",
  "NEO Baby, you're accused of being my favorite person, I'm calling the cute police.",
  "I love you more than sushi... but if we have only one bite left, we're fighting.",
  "Are you a blanket? because my heart is already racing just thinking about you. \ud83d\udc93",
  "I don't even need to work out today, and honestly I am starving. \ud83d\ude08",
  "I tolerate your weirdness absolutely perfectly. And I seriously wouldn't trade you for the world.",
  "I love you more than sushi... but please don't make me prove it by sharing.",
  "Even the cutest duck is jealous of how pretty NEO Baby is. Wait, is that too cheesy?",
  "NEO Baby, you're accused of looking too pretty today, you owe me a giant hug.",
  "I'm not a professional photographer, because I want you on top of me. \ud83e\udd75",
  "You snore cutely, but I'll never admit that out loud. Now wake up so I can annoy you. \ud83e\udd70",
  "Let's grow old and feed ducks by the lake together. Quack quack!",
  "I love your cute smile, and honestly I am starving. \ud83d\ude08",
  "Are you a duck? Because you quack me up. \ud83d\udc95",
  "You literally have my whole heart in your hands. Okay, time to go back to sleep!",
  "I love you even when you take three hours to get ready. I really hope that made you smile today!",
  "I love you more than fries... but if we have only one bite left, we're fighting.",
  "NEO Baby, you're accused of making me miss you this much, I demand a cuddle session immediately.",
  "Are you a campfire? mind if I warm them up on you? \ud83d\udc50",
  "I love you more than pizza... but please don't make me prove it by sharing.",
  "I love you more than chocolate... but if we have only one bite left, we're fighting.",
  "I love you more than cake... well, almost.",
  "You're lazier than a koala, but twice as cute. Okay, time to go back to sleep!",
  "I love you even when you take three hours to get ready. Most of the time, anyway. \ud83d\ude02",
  "I love you more than you love your morning coffee... but please don't make me prove it by sharing.",
  "Are you a blanket? because I want you on top of me. \ud83e\udd75",
  "You're looking like a whole snack today, mind if I warm them up on you? \ud83d\udc50",
  "I love you more than pancakes... and you're way sweeter too!",
  "I love you more than burgers... well, almost.",
  "I tolerate your weirdness absolutely perfectly. NEO Baby, you're stuck with me forever.",
  "I love you more than sushi... and that is saying a lot.",
  "I love you more than bubble tea... well, almost.",
  "You must be exhausted, because my heart is already racing just thinking about you. \ud83d\udc93",
  "I love your cute smile, because you've been running through my dirty mind all day. \ud83d\udca6",
  "Are you a campfire? because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "I'm not a professional photographer, because my heart is already racing just thinking about you. \ud83d\udc93",
  "I tolerate your weirdness absolutely perfectly. Most of the time, anyway. \ud83d\ude02",
  "I love you more than cake... and you're way sweeter too!",
  "You are the cutest duck in the pond. I mean it from the bottom of my heart!",
  "You're looking like a whole snack today, because you've been running through my dirty mind all day. \ud83d\udca6",
  "NEO Baby, you're accused of making me smile like an idiot, I demand a cuddle session immediately.",
  "I love you more than fries... and you're way sweeter too!",
  "I love your cute smile, because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "You're the reason I randomly check my phone and smile. But my arm is completely numb now.",
  "You're officially my favorite headache in the world. I really hope that made you smile today!",
  "You look so peaceful when you sleep. Please don't let it go to your head.",
  "NEO Baby, you're accused of being my favorite distraction, you are sentenced to a lifetime with me.",
  "You're the absolute best mistake I've ever made... wait, no. And I seriously wouldn't trade you for the world.",
  "You're totally my favorite little duckling. Quack quack!",
  "NEO Baby, you're accused of being too perfect, I demand a cuddle session immediately.",
  "Are you a blanket? but I love what's under those clothes even more. \ud83d\ude0f",
  "Stop being so ducking cute all the time. I mean it from the bottom of my heart!",
  "I love you more than I love being right. Most of the time, anyway. \ud83d\ude02",
  "You're looking like a whole snack today, because my heart is already racing just thinking about you. \ud83d\udc93",
  "You ruffle my feathers in the best way possible. \ud83e\udd86",
  "NEO Baby, you're accused of having the squishiest cheeks, you owe me a giant hug.",
  "You're the only bug I actually want in my code. And I seriously wouldn't trade you for the world.",
  "Are you a campfire? because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "You literally have my whole heart in your hands. Now wake up so I can annoy you. \ud83e\udd70",
  "I love your cute smile, but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "NEO Baby, you're accused of being too perfect, your punishment is a million kisses.",
  "I love you more than you love your morning coffee... well, almost.",
  "You're the only bug I actually want in my code. Most of the time, anyway. \ud83d\ude02",
  "You're the reason I randomly check my phone and smile. Okay, time to go back to sleep!",
  "I love you more than ice cream... but if we have only one bite left, we're fighting.",
  "You're looking like a whole snack today, because I want you on top of me. \ud83e\udd75",
  "I miss you even when you go to the kitchen. Please don't let it go to your head.",
  "You're the absolute best mistake I've ever made... wait, no. Don't tell anyone I said that, though.",
  "You're totally my favorite little duckling. \ud83d\udc95",
  "Let's grow old and feed ducks by the lake together. \ud83d\udc95",
  "You must be exhausted, because you've been running through my dirty mind all day. \ud83d\udca6",
  "You are the cutest duck in the pond. \ud83d\udc95",
  "If we were ducks, I'd share my bread with you. \ud83d\udc95",
  "I love you more than bubble tea... but if we have only one bite left, we're fighting.",
  "Are you a blanket? because you are looking super hot right now. \ud83d\udd25",
  "NEO Baby, you're accused of being illegally cute, you are sentenced to a lifetime with me.",
  "You are my absolute favorite kind of lovely chaos. NEO Baby, you're stuck with me forever.",
  "You're looking like a whole snack today, but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "Do you have a map? because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "Do you have a map? mind if I warm them up on you? \ud83d\udc50",
  "I'm not a professional photographer, because you are looking super hot right now. \ud83d\udd25",
  "Do you have a map? because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "We go together like copy and paste. And I seriously wouldn't trade you for the world.",
  "Are you a campfire? but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "NEO Baby, you're accused of having the squishiest cheeks, you are sentenced to a lifetime with me.",
  "I love you more than ice cream... but please don't make me prove it by sharing.",
  "We go together like copy and paste. Don't tell anyone I said that, though.",
  "I love your cute smile, mind if I warm them up on you? \ud83d\udc50",
  "I love you more than I love being right. I really hope that made you smile today!",
  "We go together like copy and paste. Most of the time, anyway. \ud83d\ude02",
  "I miss you even when you go to the kitchen. Now wake up so I can annoy you. \ud83e\udd70",
  "I love you more than fries... well, almost.",
  "I don't even need to work out today, but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "You're my absolute favorite notification. Please don't let it go to your head.",
  "I love you more than fries... and that is saying a lot.",
  "NEO Baby, you're accused of being my favorite person, I demand a cuddle session immediately.",
  "I love you more than cake... but please don't make me prove it by sharing.",
  "I love you more than I love being right. Don't tell anyone I said that, though.",
  "I'm not a professional photographer, because you've been running through my dirty mind all day. \ud83d\udca6",
  "I love you more than pancakes... well, almost.",
  "NEO Baby, you're accused of being my favorite distraction, I'm calling the cute police.",
  "I tolerate your weirdness absolutely perfectly. I really hope that made you smile today!",
  "You're the absolute best mistake I've ever made... wait, no. Most of the time, anyway. \ud83d\ude02",
  "NEO Baby, you're accused of having the squishiest cheeks, I'm calling the cute police.",
  "I don't even need to work out today, because my heart is already racing just thinking about you. \ud83d\udc93",
  "Do you have a map? because you are looking super hot right now. \ud83d\udd25",
  "I love waking up and knowing you exist. NEO Baby, you're simply my favorite.",
  "I'm not a professional photographer, but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "You're my absolute favorite pillow thief. Now wake up so I can annoy you. \ud83e\udd70",
  "I'm not a professional photographer, mind if I warm them up on you? \ud83d\udc50",
  "Are you a campfire? because you are looking super hot right now. \ud83d\udd25",
  "NEO Baby, you're accused of looking too pretty today, you are sentenced to a lifetime with me.",
  "You're looking like a whole snack today, because you are looking super hot right now. \ud83d\udd25",
  "Do you have a map? but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "Do you have a map? and honestly I am starving. \ud83d\ude08",
  "I love you even when you take three hours to get ready. Don't tell anyone I said that, though.",
  "Are you a blanket? because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "Do you have a map? because my heart is already racing just thinking about you. \ud83d\udc93",
  "You look so peaceful when you sleep. Okay, time to go back to sleep!",
  "You're looking like a whole snack today, because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "I love you more than pancakes... but if we have only one bite left, we're fighting.",
  "You ruffle my feathers in the best way possible. Quack quack!",
  "You are my absolute favorite kind of lovely chaos. Most of the time, anyway. \ud83d\ude02",
  "You're officially my favorite headache in the world. Most of the time, anyway. \ud83d\ude02",
  "My hands are feeling a bit cold, because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "You're totally my favorite little duckling. Wait, is that too cheesy?",
  "You're the peanut butter to my jelly. I really hope that made you smile today!",
  "I don't even need to work out today, because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "You're the only bug I actually want in my code. NEO Baby, you're stuck with me forever.",
  "I don't even need to work out today, because I want you on top of me. \ud83e\udd75",
  "My hands are feeling a bit cold, because I want you on top of me. \ud83e\udd75",
  "Are you a blanket? because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "Are you a magician? mind if I warm them up on you? \ud83d\udc50",
  "NEO Baby, you're accused of being my favorite person, you owe me a giant hug.",
  "I just want to take a nap with you forever. Please don't let it go to your head.",
  "My hands are feeling a bit cold, because my heart is already racing just thinking about you. \ud83d\udc93",
  "Stop being so ducking cute all the time. Wait, is that too cheesy?",
  "Are you a magician? but I love what's under those clothes even more. \ud83d\ude0f",
  "If we were ducks, I'd share my bread with you. \ud83e\udd86",
  "You snore cutely, but I'll never admit that out loud. Please don't let it go to your head.",
  "NEO Baby, you're accused of making me miss you this much, you owe me a giant hug.",
  "I just want to take a nap with you forever. NEO Baby, you're simply my favorite.",
  "You must be exhausted, but I love what's under those clothes even more. \ud83d\ude0f",
  "NEO Baby, you're accused of making my heart skip a beat, you owe me a giant hug.",
  "I love you more than I love being right. And I seriously wouldn't trade you for the world.",
  "I love you more than pizza... and that is saying a lot.",
  "My hands are feeling a bit cold, because you've been running through my dirty mind all day. \ud83d\udca6",
  "Are you a magician? but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "Let's grow old and feed ducks by the lake together. \ud83e\udd86",
  "Are you a campfire? because you've been running through my dirty mind all day. \ud83d\udca6",
  "You're my absolute favorite notification. But my arm is completely numb now.",
  "I love waking up and knowing you exist. But my arm is completely numb now.",
  "I love you more than chocolate... and you're way sweeter too!",
  "I love you even when you take three hours to get ready. And I seriously wouldn't trade you for the world.",
  "You're officially my favorite headache in the world. Don't tell anyone I said that, though.",
  "You're the only duck I want to waddle through life with. Quack quack!",
  "NEO Baby, you're accused of having the squishiest cheeks, your punishment is a million kisses.",
  "I don't even need to work out today, because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "NEO Baby, you're accused of looking too pretty today, your punishment is a million kisses.",
  "You're my absolute favorite pillow thief. Please don't let it go to your head.",
  "Are you a duck? Because you quack me up. Quack quack!",
  "You look so peaceful when you sleep. Now wake up so I can annoy you. \ud83e\udd70",
  "You are the only person I'd actually share my snacks with. NEO Baby, you're stuck with me forever.",
  "You're the reason I randomly check my phone and smile. Now wake up so I can annoy you. \ud83e\udd70",
  "You are my absolute favorite kind of lovely chaos. Don't tell anyone I said that, though.",
  "You ruffle my feathers in the best way possible. \ud83d\udc95",
  "I love you more than burgers... and you're way sweeter too!",
  "You're the peanut butter to my jelly. NEO Baby, you're stuck with me forever.",
  "You're looking like a whole snack today, and honestly I am starving. \ud83d\ude08",
  "I love you more than cake... and that is saying a lot.",
  "You're the only duck I want to waddle through life with. Wait, is that too cheesy?",
  "I love waking up and knowing you exist. Now wake up so I can annoy you. \ud83e\udd70",
  "I love waking up and knowing you exist. Please don't let it go to your head.",
  "I just want to take a nap with you forever. Now wake up so I can annoy you. \ud83e\udd70",
  "I'm not a professional photographer, because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "I don't even need to work out today, mind if I warm them up on you? \ud83d\udc50",
  "I love you more than sushi... and you're way sweeter too!",
  "You're lazier than a koala, but twice as cute. Now wake up so I can annoy you. \ud83e\udd70",
  "If we were ducks, I'd share my bread with you. Quack quack!",
  "I love you even when you take three hours to get ready. NEO Baby, you're stuck with me forever.",
  "You must be exhausted, and honestly I am starving. \ud83d\ude08",
  "Are you a duck? Because you quack me up. Wait, is that too cheesy?",
  "NEO Baby, you're accused of being too perfect, you owe me a giant hug.",
  "I love waking up and knowing you exist. Okay, time to go back to sleep!",
  "If we were ducks, I'd share my bread with you. Wait, is that too cheesy?",
  "You literally have my whole heart in your hands. Please don't let it go to your head.",
  "NEO Baby, you're accused of being my favorite distraction, I demand a cuddle session immediately.",
  "You're lazier than a koala, but twice as cute. NEO Baby, you're simply my favorite.",
  "I love your cute smile, because I want you on top of me. \ud83e\udd75",
  "I love you more than you love your morning coffee... but if we have only one bite left, we're fighting.",
  "You're my absolute favorite pillow thief. But my arm is completely numb now.",
  "You're the only bug I actually want in my code. Don't tell anyone I said that, though.",
  "NEO Baby, you're accused of being illegally cute, your punishment is a million kisses.",
  "You're my absolute favorite pillow thief. NEO Baby, you're simply my favorite.",
  "You snore cutely, but I'll never admit that out loud. Okay, time to go back to sleep!",
  "You look so peaceful when you sleep. NEO Baby, you're simply my favorite.",
  "If we were ducks, I'd share my bread with you. I mean it from the bottom of my heart!",
  "You're totally my favorite little duckling. I mean it from the bottom of my heart!",
  "I'm not a professional photographer, because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "NEO Baby, you're accused of stealing all my attention, I'm calling the cute police.",
  "Even the cutest duck is jealous of how pretty NEO Baby is. Quack quack!",
  "Let's grow old and feed ducks by the lake together. Wait, is that too cheesy?",
  "Are you a blanket? but I can easily picture us in bed together. \ud83d\udecf\ufe0f",
  "Stop being so ducking cute all the time. \ud83e\udd86",
  "I love you more than fries... but please don't make me prove it by sharing.",
  "Are you a blanket? and honestly I am starving. \ud83d\ude08",
  "NEO Baby, you're accused of making me smile like an idiot, your punishment is a million kisses.",
  "NEO Baby, you're accused of having the squishiest cheeks, I demand a cuddle session immediately.",
  "I just want to take a nap with you forever. Okay, time to go back to sleep!",
  "You're the absolute best mistake I've ever made... wait, no. NEO Baby, you're stuck with me forever.",
  "We go together like copy and paste. NEO Baby, you're stuck with me forever.",
  "I love you more than pizza... but if we have only one bite left, we're fighting.",
  "NEO Baby, you're accused of making me miss you this much, I'm calling the cute police.",
  "NEO Baby, you're accused of making me miss you this much, your punishment is a million kisses.",
  "NEO Baby, you're accused of making me smile like an idiot, you are sentenced to a lifetime with me.",
  "NEO Baby, you're accused of stealing all my attention, your punishment is a million kisses.",
  "You must be exhausted, mind if I warm them up on you? \ud83d\udc50",
  "I love you more than ice cream... and you're way sweeter too!",
  "You are the only person I'd actually share my snacks with. And I seriously wouldn't trade you for the world.",
  "My hands are feeling a bit cold, and honestly I am starving. \ud83d\ude08",
  "NEO Baby, you're accused of stealing all my attention, you are sentenced to a lifetime with me.",
  "You're the only bug I actually want in my code. I really hope that made you smile today!",
  "You're totally my favorite little duckling. \ud83e\udd86",
  "I love you more than burgers... but please don't make me prove it by sharing.",
  "Are you a campfire? but I love what's under those clothes even more. \ud83d\ude0f",
  "I don't even need to work out today, but I love what's under those clothes even more. \ud83d\ude0f",
  "I love you more than pizza... and you're way sweeter too!",
  "I love you more than chocolate... well, almost.",
  "You're the only duck I want to waddle through life with. \ud83e\udd86",
  "I miss you even when you go to the kitchen. Okay, time to go back to sleep!",
  "You're the peanut butter to my jelly. Don't tell anyone I said that, though.",
  "Do you have a map? because you've been running through my dirty mind all day. \ud83d\udca6",
  "I love you more than sushi... well, almost.",
  "I love you more than pancakes... but please don't make me prove it by sharing.",
  "I miss you even when you go to the kitchen. NEO Baby, you're simply my favorite.",
  "NEO Baby, you're accused of being my favorite person, you are sentenced to a lifetime with me.",
  "NEO Baby, you're accused of stealing all my attention, you owe me a giant hug.",
  "You're my absolute favorite pillow thief. Okay, time to go back to sleep!",
  "I love you more than you love your morning coffee... and that is saying a lot.",
  "I'm not a professional photographer, and honestly I am starving. \ud83d\ude08",
  "You are the only person I'd actually share my snacks with. Most of the time, anyway. \ud83d\ude02",
  "NEO Baby, you're accused of making my heart skip a beat, I demand a cuddle session immediately.",
  "NEO Baby, you're accused of stealing all my attention, I demand a cuddle session immediately.",
  "Do you have a map? but I love what's under those clothes even more. \ud83d\ude0f",
  "You're looking like a whole snack today, but I love what's under those clothes even more. \ud83d\ude0f",
  "NEO Baby, you're accused of making me smile like an idiot, I'm calling the cute police.",
  "Are you a campfire? and honestly I am starving. \ud83d\ude08",
  "NEO Baby, you're accused of being too perfect, I'm calling the cute police.",
  "NEO Baby, you're accused of making my heart skip a beat, I'm calling the cute police.",
  "You are the cutest duck in the pond. \ud83e\udd86",
  "NEO Baby, you're accused of being my favorite person, your punishment is a million kisses.",
  "You're the absolute best mistake I've ever made... wait, no. I really hope that made you smile today!",
  "Are you a duck? Because you quack me up. I mean it from the bottom of my heart!",
  "I love you more than burgers... and that is saying a lot.",
  "I love you more than burgers... but if we have only one bite left, we're fighting.",
  "My hands are feeling a bit cold, but I love what's under those clothes even more. \ud83d\ude0f",
  "My hands are feeling a bit cold, mind if I warm them up on you? \ud83d\udc50",
  "You are my absolute favorite kind of lovely chaos. And I seriously wouldn't trade you for the world.",
  "You are my absolute favorite kind of lovely chaos. I really hope that made you smile today!",
  "I love you more than ice cream... well, almost.",
  "I love your cute smile, but I love what's under those clothes even more. \ud83d\ude0f",
  "I miss you even when you go to the kitchen. But my arm is completely numb now.",
  "Are you a blanket? mind if I warm them up on you? \ud83d\udc50",
  "I'm not a professional photographer, but I love what's under those clothes even more. \ud83d\ude0f",
  "NEO Baby, you're accused of being my favorite distraction, you owe me a giant hug.",
  "Are you a magician? because you are looking super hot right now. \ud83d\udd25",
  "I love you a waddle lot. Wait, is that too cheesy?",
  "I love your cute smile, because my heart is already racing just thinking about you. \ud83d\udc93",
  "NEO Baby, you're accused of being too perfect, you are sentenced to a lifetime with me.",
  "You're the only duck I want to waddle through life with. I mean it from the bottom of my heart!",
  "Are you a blanket? because you've been running through my dirty mind all day. \ud83d\udca6",
  "I love you a waddle lot. I mean it from the bottom of my heart!",
  "I love your cute smile, because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "NEO Baby, you're accused of being illegally cute, you owe me a giant hug.",
  "You must be exhausted, because I want you on top of me. \ud83e\udd75",
  "Are you a magician? because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "NEO Baby, you're accused of looking too pretty today, I demand a cuddle session immediately.",
  "Are you a campfire? because I want you on top of me. \ud83e\udd75",
  "NEO Baby, you're accused of making my heart skip a beat, you are sentenced to a lifetime with me.",
  "Let's grow old and feed ducks by the lake together. I mean it from the bottom of my heart!",
  "We go together like copy and paste. I really hope that made you smile today!",
  "I love you more than chocolate... and that is saying a lot.",
  "You literally have my whole heart in your hands. NEO Baby, you're simply my favorite.",
  "I love you a waddle lot. \ud83d\udc95",
  "You must be exhausted, because you are looking super hot right now. \ud83d\udd25",
  "I just want to take a nap with you forever. But my arm is completely numb now.",
  "NEO Baby, you're accused of being my favorite distraction, your punishment is a million kisses.",
  "I don't even need to work out today, because you've been running through my dirty mind all day. \ud83d\udca6",
  "I tolerate your weirdness absolutely perfectly. Don't tell anyone I said that, though.",
  "You're my absolute favorite notification. Okay, time to go back to sleep!",
  "You must be exhausted, because I just keep getting lost in those beautiful eyes... and other places. \ud83d\udc40",
  "Stop being so ducking cute all the time. \ud83d\udc95",
  "I love you more than I love being right. NEO Baby, you're stuck with me forever.",
  "You're the reason I randomly check my phone and smile. NEO Baby, you're simply my favorite.",
  "I love you more than chocolate... but please don't make me prove it by sharing.",
  "You must be exhausted, because whenever I look at you, everyone else's clothes disappear! Wait, no, just yours. \ud83e\ude84",
  "You're the peanut butter to my jelly. And I seriously wouldn't trade you for the world.",
  "You're the reason I randomly check my phone and smile. Please don't let it go to your head.",
];
