const MOOD_DATA_DB = {
    "sad": {
        "emoji": "\ud83e\udd7a",
        "messages": [
            "It's completely okay to feel sad right now. I'm sitting right here with you. \ud83e\udeb4",
            "You don't have to carry this alone. I'm always holding your hand. \ud83e\udd0d",
            "You are safe with me. Take a slow, deep breath. I love you endlessly. \ud83e\udec2",
            "It's completely okay to feel sad right now. I'm sitting right here with you. \ud83e\udd7a",
            "It hurts me to see you hurt, but we will get through this together. \ud83e\udeb4",
            "It's completely okay to feel sad right now. I'm sitting right here with you. \ud83c\udf27\ufe0f",
            "You've survived 100% of your bad days. You are so much stronger than you know. \ud83e\udec2",
            "You are safe with me. Take a slow, deep breath. I love you endlessly. \ud83e\udeb4",
            "You are safe with me. Take a slow, deep breath. I love you endlessly. \ud83e\udd0d",
            "I hear you, honey. Whenever you're ready, I'm here to listen without any judgment. \ud83e\udd0d",
            "Crying is just your heart healing. Let it out, I'm right beside you. \ud83c\udf27\ufe0f",
            "You've survived 100% of your bad days. You are so much stronger than you know. \ud83e\udeb4",
            "If you need completely quiet company, I can be that for you right now. \ud83e\udd7a",
            "You are safe with me. Take a slow, deep breath. I love you endlessly. \ud83c\udf27\ufe0f",
            "I hear you, honey. Whenever you're ready, I'm here to listen without any judgment. \ud83e\udec2",
            "If you need completely quiet company, I can be that for you right now. \ud83c\udf27\ufe0f",
            "If you need completely quiet company, I can be that for you right now. \ud83e\udd0d",
            "You don't have to carry this alone. I'm always holding your hand. \ud83e\udd7a",
            "You don't have to carry this alone. I'm always holding your hand. \ud83e\udeb4",
            "Crying is just your heart healing. Let it out, I'm right beside you. \ud83e\udd7a",
            "You've survived 100% of your bad days. You are so much stronger than you know. \ud83e\udd0d",
            "You are safe with me. Take a slow, deep breath. I love you endlessly. \ud83e\udd7a",
            "Please don't rush yourself to feel better. I love you exactly as you are today. \ud83c\udf27\ufe0f",
            "Take all the time you need. Your feelings are valid, and I am so proud of you. \ud83e\udd7a",
            "Please don't rush yourself to feel better. I love you exactly as you are today. \ud83e\udec2",
            "It hurts me to see you hurt, but we will get through this together. \ud83e\udd0d",
            "It's completely okay to feel sad right now. I'm sitting right here with you. \ud83e\udd0d",
            "Take all the time you need. Your feelings are valid, and I am so proud of you. \ud83e\udec2",
            "Crying is just your heart healing. Let it out, I'm right beside you. \ud83e\udeb4",
            "You don't have to carry this alone. I'm always holding your hand. \ud83e\udec2",
            "You've survived 100% of your bad days. You are so much stronger than you know. \ud83c\udf27\ufe0f",
            "It hurts me to see you hurt, but we will get through this together. \ud83e\udd7a",
            "It's completely okay to feel sad right now. I'm sitting right here with you. \ud83e\udec2",
            "If you need completely quiet company, I can be that for you right now. \ud83e\udec2",
            "Take all the time you need. Your feelings are valid, and I am so proud of you. \ud83e\udd0d",
            "Crying is just your heart healing. Let it out, I'm right beside you. \ud83e\udd0d",
            "I hear you, honey. Whenever you're ready, I'm here to listen without any judgment. \ud83e\udd7a",
            "I hear you, honey. Whenever you're ready, I'm here to listen without any judgment. \ud83e\udeb4",
            "I hear you, honey. Whenever you're ready, I'm here to listen without any judgment. \ud83c\udf27\ufe0f",
            "You don't have to carry this alone. I'm always holding your hand. \ud83c\udf27\ufe0f",
            "It hurts me to see you hurt, but we will get through this together. \ud83c\udf27\ufe0f",
            "You've survived 100% of your bad days. You are so much stronger than you know. \ud83e\udd7a",
            "Please don't rush yourself to feel better. I love you exactly as you are today. \ud83e\udd0d",
            "Please don't rush yourself to feel better. I love you exactly as you are today. \ud83e\udd7a",
            "Take all the time you need. Your feelings are valid, and I am so proud of you. \ud83c\udf27\ufe0f",
            "Take all the time you need. Your feelings are valid, and I am so proud of you. \ud83e\udeb4",
            "Crying is just your heart healing. Let it out, I'm right beside you. \ud83e\udec2",
            "Please don't rush yourself to feel better. I love you exactly as you are today. \ud83e\udeb4",
            "It hurts me to see you hurt, but we will get through this together. \ud83e\udec2",
            "If you need completely quiet company, I can be that for you right now. \ud83e\udeb4"
        ]
    },
    "angry": {
        "emoji": "\ud83d\ude24",
        "messages": [
            "Take a deep, slow breath with me. In... and out. I'm right here. \ud83e\udec2",
            "You don't have to apologize for being upset. Your boundaries matter. \u2764\ufe0f",
            "Just remember, your peace of mind is more important than whatever caused this. \ud83c\udf3f",
            "You don't have to apologize for being upset. Your boundaries matter. \ud83e\udec2",
            "Step away for a minute and close your eyes. You deserve peace, not this stress. \ud83c\udf3f",
            "I know you're furious. I'm sending you a calming, warm hug. \ud83c\udf75",
            "It's okay to feel mad. Don't bottle it up. Let's talk about it when you're ready. \ud83d\ude24",
            "I know you're furious. I'm sending you a calming, warm hug. \ud83d\ude24",
            "Step away for a minute and close your eyes. You deserve peace, not this stress. \ud83d\ude24",
            "I'm perfectly fine just listening to you vent. Let it all out. \ud83e\udec2",
            "Whatever it is, it's not worth your beautiful energy. Let's relax together. \ud83c\udf3f",
            "It's okay to feel mad. Don't bottle it up. Let's talk about it when you're ready. \ud83e\udec2",
            "Just remember, your peace of mind is more important than whatever caused this. \u2764\ufe0f",
            "Your anger is completely justified. You have every right to feel frustrated. \ud83c\udf3f",
            "Step away for a minute and close your eyes. You deserve peace, not this stress. \ud83e\udec2",
            "I know you're furious. I'm sending you a calming, warm hug. \u2764\ufe0f",
            "It's okay to feel mad. Don't bottle it up. Let's talk about it when you're ready. \ud83c\udf3f",
            "Whatever it is, it's not worth your beautiful energy. Let's relax together. \ud83d\ude24",
            "Just remember, your peace of mind is more important than whatever caused this. \ud83d\ude24",
            "Your anger is completely justified. You have every right to feel frustrated. \ud83e\udec2",
            "I'm on your side, forever and always. We'll handle this together. \ud83c\udf3f",
            "Take a deep, slow breath with me. In... and out. I'm right here. \u2764\ufe0f",
            "I know you're furious. I'm sending you a calming, warm hug. \ud83e\udec2",
            "I'm on your side, forever and always. We'll handle this together. \ud83c\udf75",
            "Just remember, your peace of mind is more important than whatever caused this. \ud83c\udf75",
            "Take a deep, slow breath with me. In... and out. I'm right here. \ud83c\udf75",
            "Take a deep, slow breath with me. In... and out. I'm right here. \ud83c\udf3f",
            "Take a deep, slow breath with me. In... and out. I'm right here. \ud83d\ude24",
            "I'm on your side, forever and always. We'll handle this together. \ud83e\udec2",
            "Your anger is completely justified. You have every right to feel frustrated. \ud83d\ude24",
            "I'm on your side, forever and always. We'll handle this together. \u2764\ufe0f",
            "I'm perfectly fine just listening to you vent. Let it all out. \ud83c\udf3f",
            "Just remember, your peace of mind is more important than whatever caused this. \ud83e\udec2",
            "Your anger is completely justified. You have every right to feel frustrated. \u2764\ufe0f",
            "Whatever it is, it's not worth your beautiful energy. Let's relax together. \ud83c\udf75",
            "I'm perfectly fine just listening to you vent. Let it all out. \ud83c\udf75",
            "Step away for a minute and close your eyes. You deserve peace, not this stress. \ud83c\udf75",
            "I'm perfectly fine just listening to you vent. Let it all out. \ud83d\ude24",
            "Step away for a minute and close your eyes. You deserve peace, not this stress. \u2764\ufe0f",
            "I'm perfectly fine just listening to you vent. Let it all out. \u2764\ufe0f",
            "It's okay to feel mad. Don't bottle it up. Let's talk about it when you're ready. \ud83c\udf75",
            "You don't have to apologize for being upset. Your boundaries matter. \ud83d\ude24",
            "I'm on your side, forever and always. We'll handle this together. \ud83d\ude24",
            "Whatever it is, it's not worth your beautiful energy. Let's relax together. \ud83e\udec2",
            "You don't have to apologize for being upset. Your boundaries matter. \ud83c\udf3f",
            "Your anger is completely justified. You have every right to feel frustrated. \ud83c\udf75",
            "You don't have to apologize for being upset. Your boundaries matter. \ud83c\udf75",
            "It's okay to feel mad. Don't bottle it up. Let's talk about it when you're ready. \u2764\ufe0f",
            "Whatever it is, it's not worth your beautiful energy. Let's relax together. \u2764\ufe0f",
            "I know you're furious. I'm sending you a calming, warm hug. \ud83c\udf3f"
        ]
    },
    "sleepy": {
        "emoji": "\ud83d\ude34",
        "messages": [
            "You look so peaceful when you sleep. I hope you have the sweetest dreams. \u2728",
            "I'm kissing your forehead goodnight. Sleep deeply and beautifully. \u2728",
            "Every perfect day starts with a good night's sleep. Go rest your mind. \ud83d\udecc",
            "Every perfect day starts with a good night's sleep. Go rest your mind. \ud83d\ude34",
            "Every perfect day starts with a good night's sleep. Go rest your mind. \u2728",
            "Don't fight the sleepiness. The world can wait until tomorrow. \u2728",
            "Close your eyes. You've done more than enough for today. Rest now. \ud83c\udf19",
            "Your body is asking for rest. Please listen to it, my love. \ud83c\udf19",
            "Don't fight the sleepiness. The world can wait until tomorrow. \ud83c\udf19",
            "Close your eyes. You've done more than enough for today. Rest now. \ud83d\ude34",
            "Imagine me wrapping you in a warm, cozy blanket. Goodnight darling. \ud83e\udd0d",
            "Let the exhaustion fade away. I'll be here when you wake up. \ud83d\ude34",
            "Your body is asking for rest. Please listen to it, my love. \ud83d\ude34",
            "Your body is asking for rest. Please listen to it, my love. \ud83d\udecc",
            "Your body is asking for rest. Please listen to it, my love. \u2728",
            "Close your eyes. You've done more than enough for today. Rest now. \u2728",
            "I love you. Put the phone down, close your gorgeous eyes, and drift off. \ud83c\udf19",
            "Your body is asking for rest. Please listen to it, my love. \ud83e\udd0d",
            "Close your eyes. You've done more than enough for today. Rest now. \ud83d\udecc",
            "There's nothing more important right now than your sleep. Go to bed, cutie. \ud83e\udd0d",
            "You look so peaceful when you sleep. I hope you have the sweetest dreams. \ud83c\udf19",
            "Let the exhaustion fade away. I'll be here when you wake up. \ud83d\udecc",
            "Don't fight the sleepiness. The world can wait until tomorrow. \ud83e\udd0d",
            "Imagine me wrapping you in a warm, cozy blanket. Goodnight darling. \ud83d\udecc",
            "Let the exhaustion fade away. I'll be here when you wake up. \ud83e\udd0d",
            "Every perfect day starts with a good night's sleep. Go rest your mind. \ud83e\udd0d",
            "You look so peaceful when you sleep. I hope you have the sweetest dreams. \ud83e\udd0d",
            "There's nothing more important right now than your sleep. Go to bed, cutie. \u2728",
            "Imagine me wrapping you in a warm, cozy blanket. Goodnight darling. \ud83c\udf19",
            "Let the exhaustion fade away. I'll be here when you wake up. \u2728",
            "There's nothing more important right now than your sleep. Go to bed, cutie. \ud83d\ude34",
            "I love you. Put the phone down, close your gorgeous eyes, and drift off. \u2728",
            "There's nothing more important right now than your sleep. Go to bed, cutie. \ud83c\udf19",
            "Imagine me wrapping you in a warm, cozy blanket. Goodnight darling. \ud83d\ude34",
            "There's nothing more important right now than your sleep. Go to bed, cutie. \ud83d\udecc",
            "Don't fight the sleepiness. The world can wait until tomorrow. \ud83d\ude34",
            "I love you. Put the phone down, close your gorgeous eyes, and drift off. \ud83e\udd0d",
            "Imagine me wrapping you in a warm, cozy blanket. Goodnight darling. \u2728",
            "I'm kissing your forehead goodnight. Sleep deeply and beautifully. \ud83d\udecc",
            "Every perfect day starts with a good night's sleep. Go rest your mind. \ud83c\udf19",
            "Let the exhaustion fade away. I'll be here when you wake up. \ud83c\udf19",
            "I love you. Put the phone down, close your gorgeous eyes, and drift off. \ud83d\udecc",
            "Close your eyes. You've done more than enough for today. Rest now. \ud83e\udd0d",
            "I'm kissing your forehead goodnight. Sleep deeply and beautifully. \ud83c\udf19",
            "You look so peaceful when you sleep. I hope you have the sweetest dreams. \ud83d\ude34",
            "I love you. Put the phone down, close your gorgeous eyes, and drift off. \ud83d\ude34",
            "I'm kissing your forehead goodnight. Sleep deeply and beautifully. \ud83e\udd0d",
            "I'm kissing your forehead goodnight. Sleep deeply and beautifully. \ud83d\ude34",
            "Don't fight the sleepiness. The world can wait until tomorrow. \ud83d\udecc",
            "You look so peaceful when you sleep. I hope you have the sweetest dreams. \ud83d\udecc"
        ]
    },
    "happy": {
        "emoji": "\ud83e\udd70",
        "messages": [
            "I cherish these moments. Your joyful energy makes my whole week. \ud83e\udd42",
            "Whatever you're doing right now, keep doing it. You are literally glowing. \ud83c\udf89",
            "You are absolutely radiant when you're happy. Keep shining, darling. \ud83c\udf89",
            "Whatever you're doing right now, keep doing it. You are literally glowing. \ud83e\udd70",
            "I love sharing these bright, beautiful moments with you. \ud83c\udf89",
            "Your smile is my favorite thing in this entire world. Never lose it. \ud83d\udc96",
            "You are absolutely radiant when you're happy. Keep shining, darling. \ud83e\udd70",
            "Whatever you're doing right now, keep doing it. You are literally glowing. \ud83d\udc96",
            "I love sharing these bright, beautiful moments with you. \ud83e\udd70",
            "Your happiness is so contagious! I absolutely love seeing you like this. \ud83d\udc96",
            "Capture this feeling and hold onto it! You deserve every bit of this joy. \ud83d\udc96",
            "I am so incredibly happy for you. Let's celebrate this wonderful energy! \ud83c\udf89",
            "Your happiness is so contagious! I absolutely love seeing you like this. \ud83c\udf89",
            "Whatever you're doing right now, keep doing it. You are literally glowing. \ud83e\udd42",
            "Your smile is my favorite thing in this entire world. Never lose it. \ud83e\udd70",
            "Your joy is the most beautiful music to my ears. Keep being amazing! \ud83e\udd42",
            "Your smile is my favorite thing in this entire world. Never lose it. \u2600\ufe0f",
            "Your happiness is so contagious! I absolutely love seeing you like this. \u2600\ufe0f",
            "Whatever you're doing right now, keep doing it. You are literally glowing. \u2600\ufe0f",
            "Your smile is my favorite thing in this entire world. Never lose it. \ud83e\udd42",
            "Capture this feeling and hold onto it! You deserve every bit of this joy. \ud83c\udf89",
            "Seeing you thrive and smile is all I could ever ask for. \ud83e\udd42",
            "Your happiness is so contagious! I absolutely love seeing you like this. \ud83e\udd70",
            "Your joy is the most beautiful music to my ears. Keep being amazing! \ud83d\udc96",
            "Capture this feeling and hold onto it! You deserve every bit of this joy. \u2600\ufe0f",
            "I am so incredibly happy for you. Let's celebrate this wonderful energy! \ud83e\udd70",
            "I cherish these moments. Your joyful energy makes my whole week. \ud83d\udc96",
            "Seeing you thrive and smile is all I could ever ask for. \ud83d\udc96",
            "I cherish these moments. Your joyful energy makes my whole week. \u2600\ufe0f",
            "I love sharing these bright, beautiful moments with you. \ud83e\udd42",
            "You are absolutely radiant when you're happy. Keep shining, darling. \u2600\ufe0f",
            "Capture this feeling and hold onto it! You deserve every bit of this joy. \ud83e\udd42",
            "You are absolutely radiant when you're happy. Keep shining, darling. \ud83e\udd42",
            "I am so incredibly happy for you. Let's celebrate this wonderful energy! \ud83e\udd42",
            "I cherish these moments. Your joyful energy makes my whole week. \ud83e\udd70",
            "Your joy is the most beautiful music to my ears. Keep being amazing! \ud83e\udd70",
            "Seeing you thrive and smile is all I could ever ask for. \ud83e\udd70",
            "Capture this feeling and hold onto it! You deserve every bit of this joy. \ud83e\udd70",
            "Your joy is the most beautiful music to my ears. Keep being amazing! \ud83c\udf89",
            "Your happiness is so contagious! I absolutely love seeing you like this. \ud83e\udd42",
            "I cherish these moments. Your joyful energy makes my whole week. \ud83c\udf89",
            "Your joy is the most beautiful music to my ears. Keep being amazing! \u2600\ufe0f",
            "Your smile is my favorite thing in this entire world. Never lose it. \ud83c\udf89",
            "You are absolutely radiant when you're happy. Keep shining, darling. \ud83d\udc96",
            "I am so incredibly happy for you. Let's celebrate this wonderful energy! \ud83d\udc96",
            "I love sharing these bright, beautiful moments with you. \ud83d\udc96",
            "Seeing you thrive and smile is all I could ever ask for. \ud83c\udf89",
            "I am so incredibly happy for you. Let's celebrate this wonderful energy! \u2600\ufe0f",
            "I love sharing these bright, beautiful moments with you. \u2600\ufe0f",
            "Seeing you thrive and smile is all I could ever ask for. \u2600\ufe0f"
        ]
    },
    "stressed": {
        "emoji": "\ud83d\udc86\u200d\u2640\ufe0f",
        "messages": [
            "This moment of stress will pass. You are safe, and I love you deeply. \ud83d\udca7",
            "I know things feel overwhelming. Let's pause and take one small step at a time. \ud83d\udca7",
            "You are so capable and smart. This pressure doesn't define you. \ud83e\udd0d",
            "This moment of stress will pass. You are safe, and I love you deeply. \ud83c\udf3f",
            "If you need to step away from everything, do it. I'm here to support you. \ud83d\udca7",
            "You don't have to figure everything out right this second. It's okay to rest. \ud83c\udf3f",
            "Drink some water, close your eyes for 5 minutes. You'll get through this. \ud83d\udca7",
            "Drink some water, close your eyes for 5 minutes. You'll get through this. \ud83e\udd0d",
            "Drink some water, close your eyes for 5 minutes. You'll get through this. \ud83c\udf3f",
            "Let me carry some of this weight for you. You don't have to do it alone. \ud83c\udf3f",
            "You are so capable and smart. This pressure doesn't define you. \ud83e\udec2",
            "This moment of stress will pass. You are safe, and I love you deeply. \ud83e\udec2",
            "Drop your shoulders, unclench your jaw, and take a very deep breath. \ud83d\udc86\u200d\u2640\ufe0f",
            "I'm so proud of your hard work. But please remember to take care of yourself. \ud83e\udec2",
            "Drink some water, close your eyes for 5 minutes. You'll get through this. \ud83e\udec2",
            "Drink some water, close your eyes for 5 minutes. You'll get through this. \ud83d\udc86\u200d\u2640\ufe0f",
            "You don't have to figure everything out right this second. It's okay to rest. \ud83d\udca7",
            "I know things feel overwhelming. Let's pause and take one small step at a time. \ud83c\udf3f",
            "Drop your shoulders, unclench your jaw, and take a very deep breath. \ud83e\udd0d",
            "Let me carry some of this weight for you. You don't have to do it alone. \ud83d\udca7",
            "I'm so proud of your hard work. But please remember to take care of yourself. \ud83d\udca7",
            "Drop your shoulders, unclench your jaw, and take a very deep breath. \ud83d\udca7",
            "Drop your shoulders, unclench your jaw, and take a very deep breath. \ud83c\udf3f",
            "I know things feel overwhelming. Let's pause and take one small step at a time. \ud83d\udc86\u200d\u2640\ufe0f",
            "Be gentle with yourself today. You are doing the absolute best you can. \ud83e\udd0d",
            "You are so capable and smart. This pressure doesn't define you. \ud83d\udc86\u200d\u2640\ufe0f",
            "Be gentle with yourself today. You are doing the absolute best you can. \ud83c\udf3f",
            "Be gentle with yourself today. You are doing the absolute best you can. \ud83d\udc86\u200d\u2640\ufe0f",
            "Be gentle with yourself today. You are doing the absolute best you can. \ud83d\udca7",
            "This moment of stress will pass. You are safe, and I love you deeply. \ud83e\udd0d",
            "This moment of stress will pass. You are safe, and I love you deeply. \ud83d\udc86\u200d\u2640\ufe0f",
            "Be gentle with yourself today. You are doing the absolute best you can. \ud83e\udec2",
            "You don't have to figure everything out right this second. It's okay to rest. \ud83e\udec2",
            "If you need to step away from everything, do it. I'm here to support you. \ud83e\udec2",
            "You are so capable and smart. This pressure doesn't define you. \ud83c\udf3f",
            "You don't have to figure everything out right this second. It's okay to rest. \ud83d\udc86\u200d\u2640\ufe0f",
            "Let me carry some of this weight for you. You don't have to do it alone. \ud83e\udd0d",
            "You are so capable and smart. This pressure doesn't define you. \ud83d\udca7",
            "I'm so proud of your hard work. But please remember to take care of yourself. \ud83e\udd0d",
            "Drop your shoulders, unclench your jaw, and take a very deep breath. \ud83e\udec2",
            "If you need to step away from everything, do it. I'm here to support you. \ud83d\udc86\u200d\u2640\ufe0f",
            "Let me carry some of this weight for you. You don't have to do it alone. \ud83d\udc86\u200d\u2640\ufe0f",
            "I'm so proud of your hard work. But please remember to take care of yourself. \ud83c\udf3f",
            "You don't have to figure everything out right this second. It's okay to rest. \ud83e\udd0d",
            "I know things feel overwhelming. Let's pause and take one small step at a time. \ud83e\udec2",
            "If you need to step away from everything, do it. I'm here to support you. \ud83c\udf3f",
            "I know things feel overwhelming. Let's pause and take one small step at a time. \ud83e\udd0d",
            "If you need to step away from everything, do it. I'm here to support you. \ud83e\udd0d",
            "Let me carry some of this weight for you. You don't have to do it alone. \ud83e\udec2",
            "I'm so proud of your hard work. But please remember to take care of yourself. \ud83d\udc86\u200d\u2640\ufe0f"
        ]
    },
    "hungry": {
        "emoji": "\ud83e\udd24",
        "messages": [
            "Stop what you are doing. Fueling your body is priority number one. \ud83c\udf72",
            "I'd love to take you out to eat. Since I can't right now, please eat well for me! \ud83c\udf53",
            "A comfortable body comes from good food. Please go get a snack, my love. \ud83e\udd24",
            "You deserve a fantastic meal. Don't settle for less, go eat! \ud83c\udf72",
            "Hunger can mess with your mood. Eat something so you can feel perfect again. \ud83c\udf53",
            "I wish I was there to cook your favorite food. Go order something delicious! \ud83c\udf53",
            "Stop what you are doing. Fueling your body is priority number one. \ud83c\udf53",
            "I'd love to take you out to eat. Since I can't right now, please eat well for me! \ud83c\udf54",
            "A comfortable body comes from good food. Please go get a snack, my love. \ud83e\udd57",
            "A comfortable body comes from good food. Please go get a snack, my love. \ud83c\udf54",
            "Hunger can mess with your mood. Eat something so you can feel perfect again. \ud83e\udd24",
            "Don't ignore your hunger, my love. Go treat yourself to an amazing meal. \ud83e\udd57",
            "Hunger can mess with your mood. Eat something so you can feel perfect again. \ud83c\udf72",
            "You deserve a fantastic meal. Don't settle for less, go eat! \ud83c\udf54",
            "I'd love to take you out to eat. Since I can't right now, please eat well for me! \ud83e\udd24",
            "Taking care of yourself means feeding yourself well. What are you craving? \ud83e\udd57",
            "I wish I was there to cook your favorite food. Go order something delicious! \ud83c\udf54",
            "Taking care of yourself means feeding yourself well. What are you craving? \ud83c\udf72",
            "I wish I was there to cook your favorite food. Go order something delicious! \ud83e\udd57",
            "Taking care of yourself means feeding yourself well. What are you craving? \ud83c\udf53",
            "Your body needs nourishment! Please go grab something nutritious and tasty right now. \ud83e\udd57",
            "A comfortable body comes from good food. Please go get a snack, my love. \ud83c\udf72",
            "Stop what you are doing. Fueling your body is priority number one. \ud83c\udf54",
            "Hunger can mess with your mood. Eat something so you can feel perfect again. \ud83c\udf54",
            "Your body needs nourishment! Please go grab something nutritious and tasty right now. \ud83c\udf72",
            "A comfortable body comes from good food. Please go get a snack, my love. \ud83c\udf53",
            "Go nourish that beautiful body of yours. Enjoy every bite! \ud83c\udf54",
            "Your body needs nourishment! Please go grab something nutritious and tasty right now. \ud83c\udf54",
            "I'd love to take you out to eat. Since I can't right now, please eat well for me! \ud83c\udf72",
            "Go nourish that beautiful body of yours. Enjoy every bite! \ud83e\udd57",
            "I wish I was there to cook your favorite food. Go order something delicious! \ud83c\udf72",
            "Hunger can mess with your mood. Eat something so you can feel perfect again. \ud83e\udd57",
            "Taking care of yourself means feeding yourself well. What are you craving? \ud83c\udf54",
            "You deserve a fantastic meal. Don't settle for less, go eat! \ud83c\udf53",
            "Don't ignore your hunger, my love. Go treat yourself to an amazing meal. \ud83c\udf54",
            "Your body needs nourishment! Please go grab something nutritious and tasty right now. \ud83c\udf53",
            "I'd love to take you out to eat. Since I can't right now, please eat well for me! \ud83e\udd57",
            "Don't ignore your hunger, my love. Go treat yourself to an amazing meal. \ud83e\udd24",
            "Stop what you are doing. Fueling your body is priority number one. \ud83e\udd24",
            "Stop what you are doing. Fueling your body is priority number one. \ud83e\udd57",
            "You deserve a fantastic meal. Don't settle for less, go eat! \ud83e\udd24",
            "I wish I was there to cook your favorite food. Go order something delicious! \ud83e\udd24",
            "Go nourish that beautiful body of yours. Enjoy every bite! \ud83c\udf53",
            "Taking care of yourself means feeding yourself well. What are you craving? \ud83e\udd24",
            "Don't ignore your hunger, my love. Go treat yourself to an amazing meal. \ud83c\udf72",
            "You deserve a fantastic meal. Don't settle for less, go eat! \ud83e\udd57",
            "Go nourish that beautiful body of yours. Enjoy every bite! \ud83c\udf72",
            "Don't ignore your hunger, my love. Go treat yourself to an amazing meal. \ud83c\udf53",
            "Your body needs nourishment! Please go grab something nutritious and tasty right now. \ud83e\udd24",
            "Go nourish that beautiful body of yours. Enjoy every bite! \ud83e\udd24"
        ]
    }
};
